service: mff-ds

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 256
  timeout: 30

functions:
  app:
    handler: serverless.handler
    environment:
      ATLAS_URI: ${env:ATLAS_URI}
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: '{proxy+}'
          method: ANY
          cors: true
